# Generated by Django 4.0.1 on 2022-01-12 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POS', 'Posters'), ('MIS', 'Miscellaneous')], default='REC', max_length=5),
        ),
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='Classic Music', max_length=500),
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='year',
            field=models.IntegerField(default=1915, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
