# Generated by Django 4.0.1 on 2022-01-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_band_type_band_description_band_sold_band_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_type',
            new_name='type',
        ),
    ]
