# Generated by Django 4.0.1 on 2022-01-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_band_listing_description_listing_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='band',
            name='type',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
    ]
